routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GastoController;
use App\Http\Controllers\WelcomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])->name('welcome');
Route::resource('gastos', GastoController::class);

app/Models/Gasto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Gasto extends Model
{
    public $fillable = ['detalle', 'valor'];

    public function scopeDetalle($query, $detalle)
    {
        if ($detalle) {
            return $query->where('detalle', 'LIKE', "%$detalle%");
        }
    }

    public function scopeFecha($query, $fecha)
    {
        if ($fecha) {
            return $query->where('created_at', 'LIKE', "$fecha%");
        }
    }

    public function scopeValor($query, $valor)
    {
        if ($valor) {
            return $query->where('valor', '=', "$valor");
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/GastoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gasto;
use Illuminate\Http\Request;

class GastoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $detalle = $request->detalle;
        $valor = $request->valor;
        $fecha = $request->fecha;
        $gastos = Gasto::orderBy('id', 'desc')->detalle($detalle)->valor($valor)->fecha($fecha)->paginate(10);
        return view('gasto/index', compact('gastos', 'request'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('gasto/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $gastos = request()->validate([
            'detalle' => 'required',
            'valor' => 'required'
        ]);
        Gasto::create($gastos);
        return redirect()->route('gastos.index')->with('success', 'Gasto agregado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $gasto = Gasto::where(['id' => $id])->firstOrFail();
        return view('gasto/edit', compact('gasto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $gasto = Gasto::where(['id' => $id])->firstOrFail();
        $datos = request()->validate([
            'detalle' => 'required',
            'valor' => 'required'
        ]);
        $gasto->update($datos);
        return redirect()->route('gastos.index')->with('success', 'Gasto actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gasto = Gasto::where(['id' => $id])->firstOrFail();
        $gasto->delete();
        return redirect()->route('gastos.index')->with('success', 'Gasto eliminado');
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gasto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class WelcomeController extends Controller
{
    public function index()
    {
        $fecha_inicio = date('Y-m-01 00:00:00');
        $fecha_fin = date('Y-m-31 23:59:59');
        $gastos = Gasto::where('created_at', '>=', $fecha_inicio)->where('created_at', '<=', $fecha_fin)
            ->orderBy('valor', 'desc')->get();
        $total = $gastos->sum('valor');
        
        $datos = DB::select(
            'SELECT SUM(valor) as total,
            date_format(created_at, "%Y-%m") as mes from gastos
            group by mes ORDER BY mes ASC LIMIT 0, 12;'
        );
        $gastos_grafico = [];
        foreach ($datos as $key => $value) {
            $gastos_grafico[$key]['mes'] = $value->mes;
            $gastos_grafico[$key]['total'] = $value->total;
        }

        return view('welcome', compact('gastos', 'gastos_grafico', 'total'));
    }
}

resources/views/gasto/_form.blade.php
@csrf

@if($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="bi bi-exclamation-octagon-fill"></i> Por favor solucione los siguientes problemas
        <ul class="mb-0">
        @foreach ($errors->all() as $error)
            <li>{{ $error}}</li>
        @endforeach
        </ul>

        <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif
<div class="mb-3">
    <label for="detalle">Detalle</label>
    <input type="text" name="detalle" id="detalle" class="form-control {{ $errors->has('detalle') ? 'is-invalid' : '' }}" placeholder="Detalle" title="Detalle" value="{{ old('detalle', $gasto->detalle ?? '') }}">
    <span class="text-danger">{{ $errors->first('detalle') }}</span>
</div>
<div class="mb-3">
    <label for="valor">Valor</label>
    <input type="number"  min="0" name="valor" id="valor" class="form-control {{ $errors->has('valor') ? 'is-invalid' : '' }}" placeholder="Valor" title="Valor" value="{{ old('valor', $gasto->valor ?? '') }}">
    <span class="text-danger">{{ $errors->first('valor') }}</span>
</div>
<div class="mb-3">
    <input class="btn btn-dark" type="submit" value="Guardar">
</div>

resources/views/gasto/create.blade.php
@extends('../layouts.main')

@section('title', 'Crear Gasto')

@section('content')

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-chevron p-3 bg-body-tertiary rounded-3">
      <li class="breadcrumb-item">
        <a class="link-body-emphasis" href="{{ route('welcome') }}">
            <i class="bi bi-house-door-fill"></i>
          <span class="visually-hidden">Home</span>
        </a>
      </li>
      <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none" href="{{ route('gastos.index') }}">Gastos</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        Crear
      </li>
    </ol>
  </nav>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                Crear Gasto
            </div>
            <div class="card-body">
                <form action="{{ route('gastos.store') }}" method="post">
                    @csrf
                    @include('gasto._form')
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/gasto/edit.blade.php
@extends('../layouts.main')

@section('title', 'Crear Gasto')

@section('content')

<div class="container my-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-chevron p-3 bg-body-tertiary rounded-3">
      <li class="breadcrumb-item">
        <a class="link-body-emphasis" href="{{ route('welcome') }}">
            <i class="bi bi-house-door-fill"></i>
          <span class="visually-hidden">Home</span>
        </a>
      </li>
      <li class="breadcrumb-item">
        <a class="link-body-emphasis fw-semibold text-decoration-none" href="{{ route('gastos.index') }}">Gastos</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        Editar
      </li>
    </ol>
  </nav>
</div>



<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                Editar Gasto
            </div>
            <div class="card-body">
                <form action="{{ route('gastos.update', $gasto) }}" method="post">
                    @method('PUT')
                    @include('gasto._form')
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/gasto/index.blade.php
@extends('../layouts.main')

@section('title', 'Gastos')

@section('content')


@if (session('success'))
<div class="alert alert-success alert-dismissible fade show">
    {{ session('success') }}
    <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif


<div class="card">
    <div class="card-header d-flex justify-content-center">
        <h1>Gastos</h1>
    </div>
    <div class="card-body">
        <h5 class="card-title">
            <a class="btn btn-primary" href="{{ route('gastos.create') }}" title="Crear">Crear</a>
        </h5>
        <div class="card-text">
            <table class="table table-hover table-striped">
                <caption>Gastos realizados</caption>
                <thead>
                    <tr class="table-primary">
                        <th>Id</th>
                        <th>Detalle</th>
                        <th>Valor</th>
                        <th>Created</th>
                        <th>Updated</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <form action="" class="form-inline" method="GET">
                            <td>
                                <button class="btn btn-outline-dark btn-sm" type="submit"><i class='bi bi-search'></i></button>
                            </td>
                            <td>
                                <input class="form-control" type="text" name="detalle" id="detalle" value="{{ $request->detalle }}">
                            </td>
                            <td>
                                <input class="form-control" type="text" name="valor" id="valor" value="{{ $request->valor }}">
                            </td>
                            <td>
                                <input class="form-control" type="text" name="fecha" id="fecha" value="{{ $request->fecha }}">
                            </td>
                            <td></td>
                            <td>
                                <a href="{{ route('gastos.index') }}" class="btn btn-outline-primary">Limpiar</a>
                            </td>
                        </form>
                    </tr>
                    @php $total = 0 @endphp
                    @foreach($gastos as $gasto)
                    @php $total += $gasto->valor @endphp
                    <tr>
                        <td>{{ $gasto->id }}</td>
                        <td>{{ $gasto->detalle }}</td>
                        <td class="text-end">$ {{ number_format($gasto->valor, 0, ',', '.') }}</td>
                        <td>{{ $gasto->created_at }}</td>
                        <td>{{ $gasto->updated_at }}</td>
                        <td>
                            <form action="{{ route('gastos.destroy', $gasto) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <a href="{{ route('gastos.edit', $gasto) }}" class="btn btn-outline-secondary btn-sm">
                                    <i class="bi bi-pencil-fill"></i>
                                </a>
                                <button class="btn btn-danger btn-sm" type="submit"><i class="bi bi-trash3-fill"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    @if ($request->detalle or $request->valor or $request->fecha)
                    <tr class="table-dark">
                        <td></td>
                        <td class="text-end">Total</td>
                        <td class="text-end">${{ number_format($total, 0, ',', '.') }}</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-center">
        {{ $gastos->links() }}
    </div>
</div>


@endsection

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@yield('title') | {{ config('app.name') }}</title>
        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/breadcrumbs.css') }}">
        <link rel="stylesheet" href="{{ asset('css/font/bootstrap-icons.min.css') }}">
        <link href="{{ asset('img/favicon.png') }}" rel="icon" type="image/vnd.microsoft.icon"/>
    </head>
    <body>

        <div class="container">
            <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a href="{{ route('welcome') }}" class="nav-link {{ Request::path() == '/' ? 'active':'' }}"
                            aria-current="page">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('gastos.index') }}"
                            class="nav-link {{ Request::path() == 'gastos' ? 'active':'' }}">
                        Gastos
                    </a>
                </li>
            </ul>
            </header>

            <div class="content">@yield('content')</div>
        </div>

        <script src="{{ asset('js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ asset('js/color-nodes.js') }}"></script>
        <script src="{{ asset('js/chart.min.js') }}"></script>
        @yield('scripts')
    </body>
</html>